import geopandas
import momepy
import pytest

@pytest.fixture
def bucharest():
    streets = geopandas.read_file("data/bucharest.gpkg", layer="streets")
    strokes_r = geopandas.read_file("data/bucharest.gpkg", layer="strokes")
    model = {"streets": streets, "strokes_r": strokes_r}
    return model


class TestStroke:
    def test_compare_momepy(self, bucharest):
        streets = bucharest["streets"]
        strokes_r = bucharest["strokes_r"]

        continuity = momepy.COINS(streets)
        strokes_py = continuity.stroke_gdf()

        # The strokes computed by rcoins and momepy need not be strictly equal,
        # because points may be ordered in reverse, or loops may use a different starting point.
        # However, the number of strokes must be the same and all strokes generated by rcoins
        # must be within the strokes generated by momepy and vice versa.
        assert len(strokes_r) == len(strokes_py)
        assert all(strokes_r.within(strokes_py))
        assert all(strokes_r.contains(strokes_py))
