name: Render codemeta

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  # Manually trigger the Action under Actions/pkgcheck
  workflow_dispatch:
  pull_request:
    branches: [main, master]
    paths:
      - DESCRIPTION

jobs:
  render:
    name: Render codemeta
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'cm-skip')"
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install codemetar
        run: Rscript -e 'install.packages("codemetar")'

      - name: Render codemeta
        run: Rscript -e 'codemetar::write_codemeta()'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit results
        run: |
          git commit codemeta.json -m 'Re-build codemeta.json' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
